<a href="https://colab.research.google.com/github/CShorten/Small-Weaviate-Examples/blob/main/DPR_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install sentence-transformers > /dev/null

In [ ]:
text = "In Search of America: 50 Very Diverse Rock Songs About the U.S. or it could be about getting lost on tour. Your guess is as good as ours. Creedence Clearwater Revival, “Fortunate Son” Creedence Clearwater Revival left behind the swamp and the back porch for this straight-ahead indictment of the Vietnam War and the draft. There’s a clarity to the production and vocals that makes it clear the band isn’t trying for the voodoo mystery of their other hits, but instead want to hit the listener straight between the ears. IMMIGRANT SONGS (Non-Americans on America) Nick Lowe, “American Squirm” For this U.K. single that was added to the U.S. pressings of Nick"

In [ ]:
from sentence_transformers import SentenceTransformer

# These are the 6 dpr models Facebook has on HuggingFace
# dpr-reader-multiset-base and dpr-reader-single-nq-base don't seem to work

model_paths = ["facebook-dpr-ctx_encoder-single-nq-base",
               "facebook-dpr-question_encoder-single-nq-base",
               "facebook-dpr-ctx_encoder-multiset-base",
               "facebook-dpr-question_encoder-multiset-base"]

dpr_vectors = []
for model_path in model_paths:
  model = SentenceTransformer(model_path)
  dpr_vectors.append(model.encode(text))

In [ ]:
bobs_vector = [0.340567,0.04390848,-0.16423917,0.09063947,1.3811698,0.22970939,0.43797362,0.54279834,-0.10513282,-0.79637986,-0.35854185,0.3282733,-0.47877562,0.4412583,-0.03440344,0.9321354,0.47604847,0.10842317,0.23829937,-0.08295107,-0.15471894,0.20551771,-0.10383791,0.27154827,0.383335,0.07220757,0.18309963,-0.8645926,-0.9293381,-0.48766685,0.39989138,0.06842208,0.6949622,-0.60257846,-0.24497557,0.5410477,-0.30257785,0.1308937,-0.88252896,0.08151782,-0.03943849,-0.703525,-0.00088918,0.46281362,-0.37469304,0.42140478,-1.1502223,0.48907024,-0.5411483,-0.67493963,-0.20664859,-0.37589157,0.5059542,-0.09216154,0.2381466,0.32784045,-0.11808228,-0.07921243,-0.4334088,-0.6181628,0.36312705,0.510924,0.24465668,-0.70243824,-0.03385729,0.5396185,-0.24685961,0.26357543,-0.32621145,-0.35198128,0.51367545,0.14366114,-0.50909495,0.0381254,0.35489935,-0.09238255,-0.40431345,0.35561335,-0.11611545,0.38210857,-0.28271472,0.36175025,0.01421994,0.22836864,-0.14813542,-0.5410905,0.49586105,0.48944527,-0.21470678,0.17075908,0.07756257,-0.4210981,0.22693336,0.47103828,0.37960082,-0.26168573,0.64759123,0.09248483,0.42462778,0.32330573,-0.16866708,-0.34030873,-0.28467357,-0.2591642,-0.941045,0.16710818,-0.21315408,-0.4614054,-0.27937388,-0.10351473,0.12784135,0.5354625,-0.10505104,-0.7368136,-0.34931684,0.22717404,0.3335448,-0.4035673,-0.26606798,-0.39789754,0.26995665,0.75582916,0.10223925,0.26871467,0.15709782,0.15586579,0.14847434,0.29554427,-0.3879099,-0.20534337,-0.24395794,-0.16048992,-0.27726626,-0.3649212,-0.5871751,-0.18845868,0.17602164,-0.11386371,0.20104277,0.09174389,-0.46970367,-0.32630545,-0.91975343,0.08827513,0.07203829,-0.04162014,-0.17850006,0.01709032,-0.50459534,0.2549259,0.19756842,-0.00607759,-0.56184936,-0.8179135,-0.33888042,0.37655813,0.25277275,-0.29107702,0.16870952,-0.22872615,-0.19438607,0.7285079,0.49340123,-0.35155284,0.27841753,-0.42678517,-0.25959128,0.16035783,-0.56578016,-0.04647148,-0.00667036,0.02156901,0.10644317,-0.19068909,-0.03387189,-0.12559515,0.588538,0.63599324,0.16393358,0.08298612,-1.0768802,0.0519951,-0.0773977,0.04446071,-0.11339897,0.12040448,0.36343098,-0.05474865,0.3174132,0.02795982,-0.56736124,-1.030416,0.6193167,-0.55314296,0.01430702,-0.505853,-0.15661502,0.30222556,0.86453635,-0.01292717,-0.22161728,-0.07590866,0.47146183,-0.1891489,-0.830271,0.48555452,0.2600553,-0.01529896,-0.1430834,0.12686568,0.11202431,-0.403046,0.19405758,0.27850348,0.31196433,-0.2641042,-0.03259039,-0.11387312,0.6455454,0.10439253,0.49545658,0.5892171,0.40044844,0.01632166,0.07676876,1.6842184,0.2319302,-0.6511884,0.47235584,-0.40048778,-0.20235646,-0.3178882,0.5150941,-0.34310162,0.27095193,0.46958226,0.4895736,-0.01959658,0.24991518,-0.1940974,0.4741307,-0.15808716,0.10433173,0.8416345,-0.5505069,-0.24373537,0.04311019,-0.36062765,-0.08015418,-0.34382612,0.12449431,1.0215907,0.13926446,0.48838317,0.01749849,0.38129222,0.12896633,-0.5150478,0.68139297,0.07461727,-0.15247262,0.17845023,-0.06225598,0.38542956,-0.19933498,-0.649391,-0.70487106,-0.3194567,-0.09928209,0.1071589,0.2741742,0.8503246,-0.53378534,0.57751375,-0.07602286,0.59305155,0.1921711,0.36870188,-0.22075045,-0.68679726,0.27471793,0.8216343,-0.83417743,-0.38458228,-0.51068985,-0.2674495,0.02387738,-0.9766959,-0.1642946,-0.06616259,-0.07855225,0.2689258,-0.43940467,0.03728104,0.93381053,0.12510425,0.7922881,-0.21786588,0.1033904,-0.12218302,-0.69556916,0.48139256,-0.17693377,-0.23844689,0.40178218,-0.24738264,-0.12447774,-0.3251809,-8.9629755,0.04423445,-0.53859806,-0.09703434,0.37232494,0.21679854,0.09729779,-0.57046735,-0.415761,0.38037544,-0.18683118,0.75660527,-0.01813698,0.4949001,0.11509001,-0.56714666,-0.06916904,0.07673371,0.20890027,0.5062391,0.12820351,-0.2211281,-0.05621719,0.71144986,-0.04793805,-0.07023996,-0.72088575,0.85514426,-0.41237855,0.48955178,-0.1133095,0.13222682,0.27453285,-0.36101502,0.26241356,-0.02195668,0.034778,-0.62402177,0.7758998,-0.14864016,-0.12037915,-0.43521237,-0.23783302,-0.20063496,0.5735831,0.03897607,0.07077986,-0.31940055,0.1702931,1.0560415,0.14686465,-0.12952143,0.47147566,-0.32966536,0.36721253,0.09871107,0.2625811,0.31757426,-0.5842807,0.47499484,0.40395784,-0.18243444,-0.4142506,-0.41685802,0.14458436,-0.79214466,-0.42870778,-0.18093193,0.4448082,-0.3180191,-0.17413557,0.4031849,-0.2593963,-1.5531968,0.02696204,-0.14269972,0.23581094,-0.43827218,-0.7394762,0.38075662,-0.24215281,0.4548167,0.25965166,0.42544162,-0.03058833,-0.57063746,-0.7833797,-0.31135046,-0.720433,-0.37967515,0.66483724,-0.36792052,0.23921764,-0.8308329,0.5754858,0.24954927,-0.19853461,0.8762314,0.1939022,0.16161734,0.597645,-0.3948254,-0.38382167,-0.064713,-0.09161454,-0.6397895,-0.5946121,0.6508728,0.75800896,-0.7701535,0.36717862,0.40327358,-0.09653759,-0.41836977,0.34703386,0.02899039,0.4945194,-0.23002112,0.48839307,-0.31660247,0.12746131,0.32017422,-0.34404635,0.20703113,0.1643852,0.3362881,-0.07955921,-0.31590426,0.3446868,0.23079586,-0.05739683,-0.05571127,1.0506968,-0.03602815,0.4184401,-0.50466466,0.35375237,-0.51477456,-0.3484972,-0.10761517,0.51391715,0.01137424,0.38033772,0.06360722,0.5008056,-0.21126032,0.40012628,0.05584276,-0.0258795,-0.12462348,-0.16015959,-0.09757674,0.8389487,-0.02283335,-0.13133013,0.46671122,0.469244,0.18236876,-0.19648623,-0.843638,0.07950473,-0.2026341,-1.0028176,-0.39852953,-0.11309862,0.5524919,-0.08699417,-0.40079045,-0.20719826,0.46147454,0.07628846,0.08371961,-0.5423703,0.2845617,-0.2540787,0.2953043,-0.630329,-0.27202243,-0.07660782,-0.14716816,-0.23268545,0.23790038,-0.59702003,0.28649503,-0.00611126,-0.37150657,-0.11916757,-0.54874396,-0.37906933,-0.24137282,-0.36644545,0.2682743,0.66184753,0.36847025,-0.0270586,-0.43505526,-0.26614898,0.7241084,-0.15017152,0.642349,0.03883266,-0.6898842,-0.53946567,0.16463268,0.1328184,-0.43434328,1.2156408,-0.02009243,-0.7527485,0.33997893,-0.18784821,-0.29929936,0.00210881,0.5849243,0.5994647,0.16932273,0.38684803,-0.60911113,-0.17149365,-0.01643693,-0.00780219,0.3822416,0.52424514,0.31956363,-0.5492819,0.5339522,-0.34257954,-0.0081501,-0.09476805,0.2562542,0.01422119,-0.26906002,0.6100306,0.37212193,0.09482634,-0.37668943,-0.36992812,0.5577244,0.02495861,0.49598503,0.5190884,0.28438324,-0.3567624,-0.5498432,-0.44585848,0.81182027,0.34846288,-0.17345262,-0.41315842,0.3176421,-0.38567454,-0.5277392,0.11093593,-0.3812254,0.66726404,-0.11125433,-0.64850694,-0.42419356,-0.5294563,-0.09675658,0.6593744,0.20022845,-0.87655276,0.31127012,0.09352756,0.19620383,0.3012625,-0.10602093,-0.1922937,-0.6332906,-0.10331786,0.11949205,-0.24150985,0.75636435,0.08253032,0.22067797,-0.26760912,-0.01432532,0.26118642,-0.19856942,-0.29360378,0.31737673,-0.29530358,-0.11698008,0.5706959,-0.13035667,-0.29533094,0.151685,-0.25695217,0.13054633,-0.1107614,0.6904028,-0.60620147,0.1171639,-0.05942082,-0.1518265,0.42859948,0.462633,-0.56104875,0.489362,-0.3606376,0.6607245,0.3683216,-0.33446896,0.04548931,0.14100397,-0.06108868,-0.2924062,-0.22562134,0.10555398,0.17791235,-0.94724363,0.11349338,0.7624349,-0.24730515,0.29177547,0.9583404,-0.22091836,0.15267146,0.22471625,-0.03360707,-0.4117239,0.45054296,0.48627877,0.7535657,0.7094627,-0.48788142,0.18742079,1.0535178,0.9380795,0.75045377,0.06540096,0.05596679,0.17524594,-0.4441654,-0.25642395,-0.24143443,-0.89223206,-0.35734487,0.5793305,-0.0938257,0.10191721,0.37996864,0.2047196,0.29924095,0.12416589,-0.208879,-0.17583954,0.33252203,0.14024103,-0.237827,-0.26594472,-0.47880465,-0.30557644,0.5790943,-0.26783222,0.23156118,-0.01124787,-1.0791202,0.04016298,0.480658,0.31965524,0.5885316,-0.5214844,-0.20134437,-0.9210521,0.5952376,0.11922956,-0.05962908,0.3439986,0.07598054,-0.44231683,-0.12693262,-0.03389287,0.41410065,-0.66652405,0.19102973,0.01234436,-0.19470382,0.28102076,-0.4135825,-0.4401847,-0.70721674,-0.6973423,-0.25622606,-0.18298125,0.3420053,0.5319989,-0.6197445,-0.1942935,0.23719865,-0.6551973,0.05865836,0.36924154,0.05475521,-0.13576138,0.6095706,0.72477484,0.23021436,0.1443786,0.27186823,-0.06442702,-0.23102474,0.31135535,-0.18161917,0.3121524,-0.6261315,-0.19896531,-0.86601025,0.2167849,0.06809711,0.00421697,0.15189964,0.12390554,0.08711433,-0.14254135,0.8788544,0.13035417,0.1458103,-0.5625423,-0.01864636,-0.0786742,0.04301012,0.49589044,-0.71084833,0.5124771,0.1797365,0.04165649,-0.4299351,1.0169704,-0.18216646,-0.3584717,-0.51560676,0.23894334,-0.8129146,-0.6172175,-0.22919536,-0.441929,-0.21479362,0.09956443,0.7027314,-0.19214493,-0.22470975,0.0228864,0.00328922,0.6863991,-0.03306472,-0.4450106,-0.8316904,0.45607454,0.09429097,-0.00522959,0.0985508,-0.36731112,-0.06721282,-0.71430665,-0.36446977,0.5424883,-0.11941087,0.07720268]

In [ ]:
for dpr_vector in dpr_vectors:
  print(dpr_vector[:5])

[ 0.34474102  0.15467612 -0.07223491  0.22281206  0.22736852]
[0.14606573 0.02488586 0.09616219 0.1690385  0.36525133]
[ 0.21499999  0.22171749 -0.26461184 -0.11634672  0.6027113 ]
[0.14326832 0.16170213 0.01019432 0.2226799  0.47745964]


In [ ]:
# dot product distance -- higher is more similar
import numpy as np
for dpr_vector in dpr_vectors:
  print(np.dot(np.array(dpr_vector), np.array(bobs_vector)))

122.36535459962421
92.46466339907266
116.15976996990885
105.55181728504505
